export { default as Navbar } from './navbar/Navbar.jsx'
export { default as Home } from './home/Home.jsx'
export { default as Header } from './header/Header.jsx'
export { default as Footer } from './footer/Footer.jsx'
export { default as CTA } from './cta/CTA.jsx'
export { default as WhatComp } from './WhatComp/WhatComp.jsx'
export { default as Features } from './Features/Features.jsx'
export { default as Feature } from './Features/feature/Feature.jsx'
export { default as Login } from './Login/Login.jsx'
export { default as Working} from './Working/Working.jsx'
export { default as Detect} from './Detect/Detect.jsx'
export { default as Guide} from './guide/Guide.jsx'
export { default as Testimonials} from './Testimonials/Testimonials.jsx'
export { default as Card} from './Testimonials/Card/Card.jsx'
export { default as NotFound} from './NotFound/NotFound.jsx'
export { default as Dashboard} from './dashboard/Dashboard.jsx'
export { default as ChartComp } from './dashboard/Chart/ChartComp.jsx'
export { default as ProgressBar } from './Detect/ProgressBar/ProgressBar.jsx'